// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS5RAL3BiFeZzTyX5xRJv0hNpY4EadjuU',
    appId: '1:577078177166:web:01871795e51ab68175c8df',
    messagingSenderId: '577078177166',
    projectId: 'easy-shopping-01',
    authDomain: 'easy-shopping-01.firebaseapp.com',
    storageBucket: 'easy-shopping-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe7y0JEi6g1RiYcum99C6jf6C6yApIjcM',
    appId: '1:577078177166:android:d3fbbaf197dec11375c8df',
    messagingSenderId: '577078177166',
    projectId: 'easy-shopping-01',
    storageBucket: 'easy-shopping-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhcoOWENecDLzXo_hxUmUk2G3qZgG_NsI',
    appId: '1:577078177166:ios:5a38ac34b7fa35be75c8df',
    messagingSenderId: '577078177166',
    projectId: 'easy-shopping-01',
    storageBucket: 'easy-shopping-01.appspot.com',
    iosClientId: '577078177166-rnts5l3jpto8h3pltssvta026tssjgsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhcoOWENecDLzXo_hxUmUk2G3qZgG_NsI',
    appId: '1:577078177166:ios:5a38ac34b7fa35be75c8df',
    messagingSenderId: '577078177166',
    projectId: 'easy-shopping-01',
    storageBucket: 'easy-shopping-01.appspot.com',
    iosClientId: '577078177166-rnts5l3jpto8h3pltssvta026tssjgsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyShopping',
  );
}
